CREATE TABLE [dbo].[Doctor]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [FirstName] VARCHAR(30) NOT NULL,
    [MiddleName] VARCHAR(30) NULL, 
    [LastName] VARCHAR(30) NOT NULL,
    [DateOfBirth] Date NOT NULL,
    [Gender] VARCHAR(20) NOT NULL,
    [Email] VARCHAR(50) NOT NULL, 
    [Password] VARCHAR(MAX) NOT NULL,
    [Education] VARCHAR(30) NOT NULL,
    [YearsInPractice] int  NOT NULL,
    [Degree] VARCHAR(30) NOT NULL,
    [License] VARCHAR(30) NULL,
    [NpiNumber] VARCHAR(30) NULL,
    [NpiDisclosure] bit,
    [LicenseDisclosure] bit,
    [UserImage] VarBinary(Max)  NULL,
    [EducationCity] VARCHAR(30) NULL,
    [EducationCountry] VARCHAR(30) NULL,
    [EducationState] VARCHAR(30) NULL,
    [YearOfGraduation] Date NOT NULL,
    [ResidencyFrom] VARCHAR(30) NULL,
    [ResidencyCity] VARCHAR(30) NULL,
    [ResidencyCountry] VARCHAR(30) NULL,
    [ResidencyState] VARCHAR(30) NULL,
    [FellowhipFrom] VARCHAR(30) NULL,
    [FellowhipCity] VARCHAR(30) NULL,
    [FellowhipCountry] VARCHAR(30) NULL,
    [FellowhipState] VARCHAR(30) NULL,
    [IsPaid] bit Default(0),
    [IsVerified] bit Default(0)
)

