CREATE TABLE [dbo].[HospitalTimings]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[DoctorAddressId] INT NOT NULL,
	[UpdateHours] bit,
    [SunDayOpen] bit,
    [MonDayOpen] bit,
    [TuesDayOpen] bit, 
    [WednesDayOpen] bit,
    [ThursDayOpen] bit,
    [FriDayOpen] bit,
    [SatDayOpen] bit,
    [SundayStart] datetime NOT NULL,
    [SundayEnd] datetime NOT NULL,
    [MondayStart] datetime NOT NULL,
    [MondayEnd] datetime NOT NULL,
    [TuesdayStart] datetime NOT NULL,
    [TuesdayEnd] datetime NOT NULL,
    [WednesdayStart]  datetime NOT NULL,
    [WednesdayEnd] datetime NOT NULL,
    [ThursdayStart] datetime NOT NULL,
    [ThursdayEnd] datetime NOT NULL,
    [FridayStart] datetime NOT NULL,
    [FridayEnd] datetime NOT NULL,
    [SaturdayStart] datetime NOT NULL,
    [SaturdayEnd] datetime NOT NULL
)
